trigger:
  batch: true
  branches:
    include:
    - master
    - hotfix/*
    - feature/*
  paths:
    exclude:
    - LICENSE
    - readme.md

resources:
  repositories:
  - repository: sharedTemplates
    type: github
    name: f2calv/CasCap.YAMLTemplates
    endpoint: github.com_f2calv
  containers:
  - container: redis
    image: redis

variables:
- group: nuget-public
- name: buildConfiguration
  value: Release
- name: poolName
  value: AKSAgents
- name: SolutionName
  value: CasCap.Common

stages:
- stage: Build
  jobs:
  - template: templates/jobs.dotnet.build-v1.yml@sharedTemplates
    parameters:
      SolutionName: $(SolutionName)
      PublishArtifact: true

- stage: Test
  jobs:
  - job: TestJob
    container: testcontainer
    services:
      redis: redis
    steps:
    - template: templates/steps.dotnet.test-v1.yml@sharedTemplates
      parameters:
        SolutionName: $(SolutionName)
        InstallDependencies: true
        TestProjectsPath: src/

- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
  - stage: Publish
    jobs:
    - template: templates/steps.dotnet.publish.nuget-v2.yml@sharedTemplates
      parameters:
        packagesToPack: $(SolutionName)*.csproj
        #NuGetFeedUrl: https://api.nuget.org/v3/index.json
        #NuGetFeedAPIKey: $(f2calvNuGet)
        NuGetFeedUrl: https://apiint.nugettest.org/v3/index.json
        NuGetFeedAPIKey: $(f2calvNuGetInt)