trigger:
  batch: true
  branches:
    include:
    - master
    - hotfix/*
    - feature/*
  paths:
    exclude:
    - .azure-pipelines
    - LICENSE
    - README.md

resources:
  repositories:
  - repository: sharedTemplates
    type: github
    name: f2calv/CasCap.YAMLTemplates
    endpoint: github.com_f2calv
  containers:
  - container: redis
    image: redis
    ports:
    - 6379:6379

variables:
- group: nuget-public
- name: buildConfiguration
  value: Release
- name: poolName
  value: AKSAgents
- name: SolutionName
  value: CasCap.Common

stages:
- stage: Build
  jobs:
  - template: templates/jobs.dotnet.build-v1.yml@sharedTemplates
    parameters:
      SolutionName: $(SolutionName)
      PublishArtifact: true

- stage: Test
  jobs:
  - job: TestJob
    services:
      redis: redis
    steps:

    - template: templates/steps.dotnet.test-v1.yml@sharedTemplates
      parameters:
        SolutionName: $(SolutionName).sln
        InstallDependencies: true
        TestProjectsPath: src/

- stage: Publish
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
  - job: PublishJob
    variables:
      Version.Major: 1
      Version.Minor: 0
      Version.PackageMajorMinor: $(Version.Minor).$(Version.Major)-$(SolutionName)
      Version.Revision: $[counter(variables['Version.PackageMajorMinor'], 0)]
      PackageVersion: $(Version.Major).$(Version.Minor).$(Version.Revision)
    steps:
    - template: templates/steps.dotnet.publish.nuget-v2.yml@sharedTemplates
      parameters:
        packagesToPack: $(SolutionName)*.csproj
        NuGetFeedUrl: https://api.nuget.org/v3/index.json
        NuGetFeedAPIKey: $(f2calvNuGet)
        #NuGetFeedUrl: https://apiint.nugettest.org/v3/index.json
        #NuGetFeedAPIKey: $(f2calvNuGetInt)