trigger:
  batch: true
  branches:
    include:
    - master
    - hotfix/*
    - feature/*
  paths:
    #include:
    #- .azure-pipelines/CasCap.Common
    #- src/CasCap.Common.Caching
    #- src/CasCap.Common.Extensions
    #- src/CasCap.Common.Logging
    #- src/CasCap.Common.Net
    #- src/CasCap.Common.Serialisation.Json
    #- src/CasCap.Common.Serialisation.MessagePack
    #- src/CasCap.Common.Threading
    exclude:
    - readme.md

resources:
  repositories:
  - repository: sharedTemplates
    type: github
    name: f2calv/CasCap.YAMLTemplates
    endpoint: github.com_f2calv

variables:
- group: nuget-public
- name: buildConfiguration
  value: Release
- name: poolName
  value: AKSAgents
- name: SolutionName
  value: CasCap.Common

stages:
- stage: Build
  jobs:
  - template: templates/jobs.dotnet.build-v1.yml@sharedTemplates
    parameters:
      SolutionName: $(SolutionName)
      PublishArtifact: true

- stage: Test
  jobs:
  - template: templates/jobs.dotnet.test-v1.yml@sharedTemplates
    parameters:
      SolutionName: $(SolutionName)
      InstallDependencies: true

- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
  - stage: Publish
    jobs:
    - template: templates/steps.dotnet.publish.nuget-v2.yml@sharedTemplates
      parameters:
        packagesToPack: $(SolutionName)*.csproj
        #NuGetFeedUrl: https://api.nuget.org/v3/index.json
        #NuGetFeedAPIKey: $(f2calvNuGet)
        NuGetFeedUrl: https://apiint.nugettest.org/v3/index.json
        NuGetFeedAPIKey: $(f2calvNuGetInt)
        #NuGetFeedUrl: https://pkgs.dev.azure.com/cascap/CAS/_packaging/MyInternal2/nuget/v3/index.json
        #NuGetFeedAPIKey: VSTS